package com.example.springbootdemo.pojo;

import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_id
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goods_id
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_no
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    private Integer orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.created_by
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.modified_by
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    private String modifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.created_at
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.modified_at
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    private Date modifiedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_id
     *
     * @return the value of orders.user_id
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_id
     *
     * @param userId the value for orders.user_id
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.goods_id
     *
     * @return the value of orders.goods_id
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.goods_id
     *
     * @param goodsId the value for orders.goods_id
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_no
     *
     * @return the value of orders.order_no
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_no
     *
     * @param orderNo the value for orders.order_no
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.created_by
     *
     * @return the value of orders.created_by
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.created_by
     *
     * @param createdBy the value for orders.created_by
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.modified_by
     *
     * @return the value of orders.modified_by
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.modified_by
     *
     * @param modifiedBy the value for orders.modified_by
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.created_at
     *
     * @return the value of orders.created_at
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.created_at
     *
     * @param createdAt the value for orders.created_at
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.modified_at
     *
     * @return the value of orders.modified_at
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    public Date getModifiedAt() {
        return modifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.modified_at
     *
     * @param modifiedAt the value for orders.modified_at
     *
     * @mbg.generated Wed Dec 13 22:34:13 CST 2023
     */
    public void setModifiedAt(Date modifiedAt) {
        this.modifiedAt = modifiedAt;
    }
}